name: Sync labels

on:
  push:
    # masterに修正反映。かつ、関連ファイルに修正があった場合のみ実行する
    branches:
      - develop
    paths:
      - '.github/labels.yml'
      - '.github/workflows/label_sync.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: crazy-max/ghaction-github-labeler@v1.1.1
        with:
          yaml_file: '.github/labels.yml'
          skip_delete: true # 定義ファイルに記載の無いラベルの削除を行わない
          dry_run: false # 実際に反映する。trueの場合は、結果のみ表示で反映しない。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
